try {
  let a
  a.map(item => item.name)
} catch(e) {
  console.log('error', e)
}